"""empty message

Revision ID: 8d211a5474f0
Revises: 48c4e5572054
Create Date: 2020-03-04 15:08:24.925424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d211a5474f0'
down_revision = '48c4e5572054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_table('source')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=20), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=120), nullable=True),
    sa.Column('address2', sa.VARCHAR(length=120), nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('source', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('referral_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ssn', sa.NUMERIC(precision=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dob', sa.DATETIME(), nullable=True),
    sa.Column('poa', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=120), nullable=True),
    sa.Column('poa_address1', sa.VARCHAR(length=120), nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('medicare', sa.NUMERIC(precision=255), nullable=True),
    sa.Column('secondary', sa.NUMERIC(precision=255), nullable=True),
    sa.Column('discharge_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('disc_slp', sa.BOOLEAN(), nullable=True),
    sa.Column('disc_ot', sa.BOOLEAN(), nullable=True),
    sa.Column('disc_pt', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_oral', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_speech', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_cognitive', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_caregiver', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_dementia', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_adl', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_safety', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_upper_extremity', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_ther_exercise', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_balance', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_ther_activity', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_coordination', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_transfer', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_range', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_massage', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_pain', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_wheelchair', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_lower_extremity', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_cane', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_postural', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_gait', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_other', sa.BOOLEAN(), nullable=True),
    sa.Column('treat_other_desc', sa.VARCHAR(length=120), nullable=True),
    sa.Column('med_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('med_firstname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('med_lastname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('med_npi', sa.VARCHAR(length=10), nullable=True),
    sa.Column('med_address1', sa.VARCHAR(length=120), nullable=True),
    sa.Column('med_address2', sa.VARCHAR(length=120), nullable=True),
    sa.Column('med_city', sa.VARCHAR(length=20), nullable=True),
    sa.Column('med_state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('med_zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('med_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('med_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('med_fax', sa.VARCHAR(length=20), nullable=True),
    sa.Column('referral_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('disc_ot IN (0, 1)'),
    sa.CheckConstraint('disc_pt IN (0, 1)'),
    sa.CheckConstraint('disc_slp IN (0, 1)'),
    sa.CheckConstraint('treat_adl IN (0, 1)'),
    sa.CheckConstraint('treat_balance IN (0, 1)'),
    sa.CheckConstraint('treat_cane IN (0, 1)'),
    sa.CheckConstraint('treat_caregiver IN (0, 1)'),
    sa.CheckConstraint('treat_cognitive IN (0, 1)'),
    sa.CheckConstraint('treat_coordination IN (0, 1)'),
    sa.CheckConstraint('treat_dementia IN (0, 1)'),
    sa.CheckConstraint('treat_gait IN (0, 1)'),
    sa.CheckConstraint('treat_lower_extremity IN (0, 1)'),
    sa.CheckConstraint('treat_massage IN (0, 1)'),
    sa.CheckConstraint('treat_oral IN (0, 1)'),
    sa.CheckConstraint('treat_other IN (0, 1)'),
    sa.CheckConstraint('treat_pain IN (0, 1)'),
    sa.CheckConstraint('treat_postural IN (0, 1)'),
    sa.CheckConstraint('treat_range IN (0, 1)'),
    sa.CheckConstraint('treat_safety IN (0, 1)'),
    sa.CheckConstraint('treat_speech IN (0, 1)'),
    sa.CheckConstraint('treat_ther_activity IN (0, 1)'),
    sa.CheckConstraint('treat_ther_exercise IN (0, 1)'),
    sa.CheckConstraint('treat_transfer IN (0, 1)'),
    sa.CheckConstraint('treat_upper_extremity IN (0, 1)'),
    sa.CheckConstraint('treat_wheelchair IN (0, 1)'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
