"""empty message

Revision ID: bf3503d2e2ae
Revises: 
Create Date: 2020-03-06 10:00:52.102401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3503d2e2ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address1', sa.String(length=120), nullable=True),
    sa.Column('address2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('ssn', sa.BINARY(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('poa', sa.String(length=120), nullable=True),
    sa.Column('poa_phone', sa.String(length=120), nullable=True),
    sa.Column('poa_address1', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('medicare', sa.BINARY(length=255), nullable=True),
    sa.Column('secondary', sa.BINARY(length=255), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('disc_slp', sa.Boolean(), nullable=True),
    sa.Column('disc_ot', sa.Boolean(), nullable=True),
    sa.Column('disc_pt', sa.Boolean(), nullable=True),
    sa.Column('treat_oral', sa.Boolean(), nullable=True),
    sa.Column('treat_speech', sa.Boolean(), nullable=True),
    sa.Column('treat_cognitive', sa.Boolean(), nullable=True),
    sa.Column('treat_caregiver', sa.Boolean(), nullable=True),
    sa.Column('treat_dementia', sa.Boolean(), nullable=True),
    sa.Column('treat_adl', sa.Boolean(), nullable=True),
    sa.Column('treat_safety', sa.Boolean(), nullable=True),
    sa.Column('treat_upper_extremity', sa.Boolean(), nullable=True),
    sa.Column('treat_ther_exercise', sa.Boolean(), nullable=True),
    sa.Column('treat_balance', sa.Boolean(), nullable=True),
    sa.Column('treat_ther_activity', sa.Boolean(), nullable=True),
    sa.Column('treat_coordination', sa.Boolean(), nullable=True),
    sa.Column('treat_transfer', sa.Boolean(), nullable=True),
    sa.Column('treat_range', sa.Boolean(), nullable=True),
    sa.Column('treat_massage', sa.Boolean(), nullable=True),
    sa.Column('treat_pain', sa.Boolean(), nullable=True),
    sa.Column('treat_wheelchair', sa.Boolean(), nullable=True),
    sa.Column('treat_lower_extremity', sa.Boolean(), nullable=True),
    sa.Column('treat_cane', sa.Boolean(), nullable=True),
    sa.Column('treat_postural', sa.Boolean(), nullable=True),
    sa.Column('treat_gait', sa.Boolean(), nullable=True),
    sa.Column('treat_other', sa.Boolean(), nullable=True),
    sa.Column('treat_other_desc', sa.String(length=120), nullable=True),
    sa.Column('med_type', sa.String(length=50), nullable=True),
    sa.Column('med_firstname', sa.String(length=50), nullable=True),
    sa.Column('med_lastname', sa.String(length=50), nullable=True),
    sa.Column('med_npi', sa.String(length=10), nullable=True),
    sa.Column('med_address1', sa.String(length=120), nullable=True),
    sa.Column('med_address2', sa.String(length=120), nullable=True),
    sa.Column('med_city', sa.String(length=50), nullable=True),
    sa.Column('med_state', sa.String(length=2), nullable=True),
    sa.Column('med_zip_code', sa.String(length=10), nullable=True),
    sa.Column('med_email', sa.String(length=120), nullable=True),
    sa.Column('med_phone', sa.String(length=50), nullable=True),
    sa.Column('med_fax', sa.String(length=50), nullable=True),
    sa.Column('referral_status', sa.String(length=50), autoincrement=True, nullable=True),
    sa.Column('referral_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_table('user')
    op.drop_table('source')
    # ### end Alembic commands ###
