"""empty message

Revision ID: fff307bc6259
Revises: bf3503d2e2ae
Create Date: 2020-03-06 18:36:01.977633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff307bc6259'
down_revision = 'bf3503d2e2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job_type')
    # ### end Alembic commands ###
